apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: meureplicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata: 
      name: meupod
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: kubedevio/web-page:blue
          ports:
            - containerPort: 80